version: '3'

services:
  chatgpt-server:
    build: .
    image: chatgpt/server
    container_name: chatgpt-server
    ports:
      - '3002:3002'
    env_file: ./openai.conf

  nginx:
    image: nginx
    container_name: chatgpt-nginx
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - chatgpt-server
    command: [ "nginx", "-g", "daemon off;" ]
