version: '3.9'

services:
  chatgpt-server:
    build:
      context: ./pserver
      dockerfile: Dockerfile
    image: chatgpt/pserver
    container_name: chatgpt-pserver
    ports:
      - '5001:5001'
    env_file: ./openai.env
    environment:
      TIMEOUT_MS: 60000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-server
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/data/chatgpt/log:/var/log/nginx
      - /var/data/chatgpt/passwd.db:/etc/nginx/passwd.db
      - /var/data/chatgpt/cert:/etc/nginx/cert
    links:
      - chatgpt-server
    command: [ "nginx", "-g", "daemon off;" ]
