version: '3.9'

services:
  chatgpt-server:
    build:
      context: .
      dockerfile: application/Dockerfile
    image: chatgpt/application
    container_name: chatgpt-application
    ports:
      - '5001:5001'
    env_file: ./openai.env
    environment:
      TIMEOUT_MS: 60000
    volumes:
      - /var/data/chatgpt/log:/var/logs
    command: [ "gunicorn", "-c", "gunicorn_conf.py", "server:app" ]

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: chatgpt/nginx
    container_name: chatgpt-nginx
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/data/chatgpt/log:/var/log/nginx
      - /var/data/chatgpt/cert:/etc/nginx/cert
    links:
      - chatgpt-server
    depends_on:
      - chatgpt-server
    command: [ "nginx", "-g", "daemon off;" ]
